# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: Frontend
  items:
    - label: Simple HTML
      link: /starters/html
    - label: Vanilla.js
      link: /starters/vanillajs
    - label: Basic React.js
      link: /starters/react
    - label: React with Routing
      link: /starters/flux

- label: Backend
  items:
    - label: Python Flask
      link: /starters/flask
    - label: Express (Node)
      link: /starters/express
    - label: React & Flask (Full-Stack)
      link: /starters/react-flask
    - label: Postgres DB
      link: /backend/database

- label: Deploy
  items:  
    - label: To Render.com
      link: /deploy/render
    - label: To Heroku + Postgres
      link: /deploy/heroku-postgress
    - label: To Heroku + MySQL
      link: /deploy/heroku-mysql
      
- label: Other
  items:
    - label: Upload user images
      link: /tutorials/upload-images
    - label: API Validations in Flask
      link: /backend/api-validations
    - label: Changelog
      link: /other/changelog
    - label: 'Github'
      link: https://github.com/4GeeksAcademy/Templates-Boilerplates
