# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Frontend
  items:
    - label: Simple HTML
      link: /starters/html
    - label: Vanilla.js
      link: /starters/vanillajs
    - label: React.js
      link: /starters/react

- label: Backend in Python
  items:
    - label: Flask API Starter
      link: /starters/flask
    - label: The database
      link: /backend/database
    - label: API Validations
      link: /backend/api-validations

- label: Backend in Node
  items:
    - label: Express API (Node)
      link: /starters/express

- label: Full Stack
  items:  
    - label: React + Flask (Full Stack)
      link: /starters/full-stack
    - label: How to work with images in your database
      link: /tutorials/upload-images
    - label: Deploy to heroku with Posgres
      link: /backend/deploy-heroku-posgres
    - label: Deploy to heroku with MySQL
      link: /backend/deploy-heroku-mysql
      
- label: Other
  items:
    - label: FAQ
      link: /other/faq
    - label: Changelog
      link: /other/changelog
    - label: 'Github'
      link: https://github.com/4GeeksAcademy/Templates-Boilerplates
